Remove ACTIVE from default state filters
tenchi-security/zanshin-cli pull request #57
Opened 2022-12-06 20:56 UTC by asieira

Since ACTIVE is just an alias for including OPEN and IN_PROGRESS, it is redundant to add it to the default state filters.

2022-12-07 19:57 UTC, edpin requested changes
I think something automatic got triggered and the ACTIVE state still shows up in the documentation, it's just not in the default anymore. Is that the desired end state?

2022-12-07 19:57 UTC, edpin commented on CLI.md
> +* `--states [OPEN|ACTIVE|IN_PROGRESS|RISK_ACCEPTED|MITIGATING_CONTROL|FALSE_POSITIVE|CLOSED]`: Only list alerts in the specified states.  [default: OPEN, IN_PROGRESS, RISK_ACCEPTED, MITIGATING_CONTRO
It still shows ACTIVE here.

2022-12-07 19:57 UTC, edpin commented on CLI.md
> +* `--states [OPEN|ACTIVE|IN_PROGRESS|RISK_ACCEPTED|MITIGATING_CONTROL|FALSE_POSITIVE|CLOSED]`: Only list alerts in the specified states.  [default: OPEN, IN_PROGRESS, RISK_ACCEPTED, MITIGATING_CONTRO
Still shows ACTIVE.

2022-12-07 19:57 UTC, edpin commented on CLI.md
> +* `--state [OPEN|ACTIVE|IN_PROGRESS|RISK_ACCEPTED|MITIGATING_CONTROL|FALSE_POSITIVE|CLOSED]`: Only list alerts in the specified states.  [default: OPEN, IN_PROGRESS, RISK_ACCEPTED, MITIGATING_CONTROL
Same here.

2022-12-07 19:57 UTC, edpin commented on CLI.md
> +* `--state [OPEN|ACTIVE|IN_PROGRESS|RISK_ACCEPTED|MITIGATING_CONTROL|FALSE_POSITIVE|CLOSED]`: Only list alerts in the specified states.  [default: OPEN, IN_PROGRESS, RISK_ACCEPTED, MITIGATING_CONTROL
And here, and all the ones below.

2022-12-08 01:46 UTC, asieira commented
> I think something automatic got triggered and the ACTIVE state still shows up in the documentation, it's just not in the default anymore. Is that the desired end state?

It is, since it's still listed as an accepted value in the [API documentation](https://api.zanshin.tenchisecurity.com/#tag/Alerts/operation/listAllAlert), so the SDK and CLI should still allow it.

2022-12-08 21:40 UTC, edpin approved these changes

2022-12-09 12:24 UTC, lschanner-tenchi approved these changes

2022-12-09 12:34 UTC, merged