add feat to get an organization scan target group
tenchi-security/zanshin-cli pull request #61
Opened 2022-12-29 21:56 UTC by Isafagioli-Tenchi

added method to get a scan target group

2022-12-30 16:26 UTC, asieira submitted a review, later dismissed

2023-01-09 22:29 UTC, edpin requested changes

2023-01-09 22:29 UTC, edpin commented on zanshincli/main.py
> +    Gets the scan target groups of the organization user.
I think you mean: "Gets the scan targets for the given scan target group" (it lists scan targets right, not groups?)

2023-01-09 22:42 UTC, edpin approved these changes

2023-01-17 03:19 UTC, edpin approved these changes

2023-01-17 15:01 UTC, RomuloGatto approved these changes

2023-01-17 15:02 UTC, merged