Feat/pre commit
tenchi-security/zanshin-cli pull request #74
Opened 2023-01-26 15:55 UTC by Isafagioli-Tenchi

added pre commit and its changes

2023-01-31 16:44 UTC, asieira requested changes
The biggest advantage of the pre-commit checks is when they are configured locally by each developer so sensitive data and other problems don't even make it into Github. 

So even though I like that we are running the tests in CI as well, the most important thing for me would be to create documentation telling CLI *developers* how to set up pre-commit hooks for this repo on their machines. CONTRIBUTING.md, maybe?

2023-01-31 22:26 UTC, RomuloGatto commented
> The biggest advantage of the pre-commit checks is when they are configured locally by each developer so sensitive data and other problems don't even make it into Github.
> 
> So even though I like that we are running the tests in CI as well, the most important thing for me would be to create documentation telling CLI _developers_ how to set up pre-commit hooks for this repo on their machines. CONTRIBUTING.md, maybe?

I guess the idea of CONTRIBUTING.md is different. What you are saying could easily be inserted at the README.md, on the installation or configuration step. What do you think?

2023-02-06 19:11 UTC, RomuloGatto commented
@asieira I've added some data to the newly created `CONTRIBUTING.md`, please, take a look.

2023-02-07 21:33 UTC, edpin approved these changes

2023-02-14 20:24 UTC, RomuloGatto approved these changes

2023-02-14 20:24 UTC, merged